### PR TITLE
Components to interface with cannon api: sleep, collision filtering, and a collider

### PR DESCRIPTION
**Pull request by wmurphyrd**
Here are some cannon api interface components I created for my Adit app. Are you interested in adding them to aframe-physics-system?

# sleepy
* Uses the `sleep` api to make dynamic bodies stay put when idle. Very useful for zero-gravity UI so that things don't float away when dropped or bumped
* Can be configured to dampen only position so that objects can be set to spin in place when dropped with a twisting force (or vice versa if you wanted persistent lateral translation without rotation)

# physics-collision-filter (component + system)
* Interfaces the `body.collisionFilterGroup` and `body.collisionFilterMask` properties
* The system abstracts away the binary math using strings for group identifiers, automatically collecting each new group as it is used and assigning it a bit location
* Can improve performance by limiting number of collision checks performed

# physics-collider
* Take advantage of the collision calculations from cannon to manage `collided` state for entities with physics bodoes
* Replacement for `aframe-extras.sphere-collider` with better performance compared to running both physics and the sphere collider calculations. 
* Uses `physics-collision-filter` to automatically manage collide-able objects; no more need for tracking down the colliders to call `update()` when dynamically adding entities to the scene

An example scene showing these in action is available at: https://wmurphyrd.github.io/aframe-physics-system/examples/interfaces.html **Browser version note:** These won't work in the latest WebVR Chromium build due to the time calculation error but do work in the September 23rd WebVR Chromium v.55 build. 

These do still need work before they could be included. (I'm brand new to JS so I still need to figure out  node and unit testing in particular). Let me know if you're interested

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks for the PR! I'll need to think about these for a while. One of the next features I'm planning will be to support running CannonJS in a web worker, and that will change the API surface, so I don't want to merge anything until I'm sure it won't break when that happens.

**Comment by wmurphyrd** [comment]
I spun these off into their own package. If you're interested, I'd be happy merge them into `aframe-physics-system` at a later date, maybe once they've matured some from user feedback

https://github.com/wmurphyrd/aframe-physics-extras

**Comment by donmccurdy** [comment]
Yeah sorry for the delay — I was testing out the sleep API and it seems like static bodies don't wake up dynamic bodies when they collide? i've been using static bodies for controllers, so that seemed like a problem and I haven't had time to work through it.

May also want to put a note at the top of the readme specifying can be used with this repo OR aframe-extras (and not, say, Kevin's physics) – people get confused about physics being already in aframe-extras :)

**Comment by wmurphyrd** [comment]
Yeah that factor of the sleep API is a problem. I'm currently changing the controller's `body.type` to kinematic (in `physics-collider`) to bypass it, but that has other consequences. I'm thinking of dropping the actual sleep from sleepy and just using the damping by default which accomplishes mostly the same thing (but without the potential performance gains of sleep). 

Adding compatibility info is good advice - I'd forgotten there are other physics options.

**Comment by donmccurdy** [comment]
> I'm currently changing the controller's body.type to kinematic (in physics-collider) to bypass it, but that has other consequences.

That's what I'd been hoping to test yeah... what sort of side effects? I'm mostly interested in the performance side, have some example scenes that the sleep API would help a lot.

Not sure what you prefer in terms of maintaining things — I'm certainly fine with you keeping a separate repo of course, or glad to work through issues as time allows. If the `collision-filter` features were a separate PR and used properties of the `dynamic-` and `static-body` components I'd be happy to merge that part any time.

**Comment by wmurphyrd** [comment]
>That's what I'd been hoping to test yeah... what sort of consequences? 

It works perfectly for grabbing objects and moving them with constraints, but it ghosts through all bodies without disturbing them so you can't slap or push things around. I'd originally intended `physics-collider.collisionPhysics`/`body.collisionResponse` to be something you could toggle to either bump things around or reach into them and grab, but that's not working right now. 

>If the collision-filter features were a separate PR and used properties of the dynamic- and static-body components I'd be happy to merge that part any time.

I bet using the body components would help with cross-driver compatibility, too. Are you picturing it as as new schema properties added to the `body` component and dropping `collision-filter` as a separate component? (and, if so, would the system functionality be rolled into the `physics` system?)

**Comment by wmurphyrd** [comment]
I solved the kinematic body sleep issue! The problem was that the [wake-up check](https://github.com/donmccurdy/cannon.js/blob/022e8ba53fa83abf0ad8a0e4fd08623123838a17/src/world/World.js#L782) for other bodies depends on the velocity of the kinematic body which is always zero in the case of the controllers. Just had to lower the `sleepSpeedLimit` on the controller bodies to 0 and now it works flawlessly ([demo here](https://wmurphyrd.github.io/aframe-physics-extras/examples/collision_response/)). 

I also found another way to monitor the collisions so that I can report kinematic-to-static collisions in `physics-collider` which should be handy for setting up miscellaneous collisions zones for interactivity in scenes or maybe for limiting player movement (although I agree nav-mesh is a better direction for that case).

**Comment by donmccurdy** [comment]
Awesome, thanks! It sounds like kinematic bodies would be better for controllers than the static bodies i’ve been recommending then. Will try to get this worked into a future release then... i’m hoping to move toward nav meshes for player movement but still need to get support for the sleep API in here also.

**Comment by donmccurdy** [comment]
Filed a couple issues to track these one by one... i think sleep API is highest priority for me, but may depend on kinematic bodies first.

**Pull request closed without merging**
